"""Add comments, ratings, and price to brands

Revision ID: 1215a8d67de7
Revises: 09993f4414fe
Create Date: 2023-12-13 11:34:31.387803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1215a8d67de7'
down_revision: Union[str, None] = '09993f4414fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'price')
    # ### end Alembic commands ###
