"""Add brand_id columns

Revision ID: b598589cf79a
Revises: be713140f1af
Create Date: 2023-12-13 21:52:58.261316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b598589cf79a'
down_revision = 'be713140f1af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_brands_customers', 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comments_brands', 'brands', ['brand_id'], ['id'])

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ratings_brands', 'brands', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ratings_brands', type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_brands', type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint('fk_brands_customers', type_='foreignkey')

    # ### end Alembic commands ###
