"""adding customer tables in brands

Revision ID: be713140f1af
Revises: ecfbb79b9ed3
Create Date: 2023-12-13 20:03:38.613589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be713140f1af'
down_revision = 'ecfbb79b9ed3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the 'customer_id' column already exists in the 'brands' table, and if not, add it
    conn = op.get_bind()
    inspector = sa.engine.reflection.Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('brands')]
    if 'customer_id' not in columns:
        op.add_column('brands', sa.Column('customer_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'brands', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    
    conn = op.get_bind()
    inspector = sa.engine.reflection.Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('brands')]
    if 'customer_id' in columns:
        op.drop_constraint(None, 'brands', type_='foreignkey')
        op.drop_column('brands', 'customer_id')
    # ### end Alembic commands ###
