"""Add columns to Customer table

Revision ID: ecfbb79b9ed3
Revises: 
Create Date: 2023-12-13 17:47:30.124762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfbb79b9ed3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_brand_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_brand_association',
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('brand_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], )
    )
    # ### end Alembic commands ###
